baseurl = "http://aimless.jp/"
languageCode = "ja"
title = "Aimless"
disqusShortname = "aimlessjpblog"
rssuri = "feed"

[Params]
subtitle = "Powered by aimless emotion"
twitter = "https://twitter.com/kongou_ae"
github = "https://github.com/kongou-ae"
copyright = "Written by kongou_ae"
analytics = "UA-1736780-2"
