baseurl = "https://aimless.jp/blog/"
languageCode = "ja"
title = "Aimless"
disqusShortname = "aimlessjpblog"
copyright = "Written by kongou_ae"
canonifyurls = false
pygmentsStyle = "monokai"
pygmentsUseClasses = true
pygmentscodefences = true

[Params]
twitter = "kongou_ae"
github = "kongou-ae"
googleAnalyticsUserID = "UA-1736780-2"

[outputs]
home = [ "HTML", "RSS" ]

[outputFormats]
[outputFormats.RSS]
baseName = "feed"
