[context.production.environment]
  HUGO_VERSION = "0.31.1"

[context.deploy-preview]
  publish = "public"
  command = "hugo --buildFuture -t hugo-primer-fork -d public/blog && mv public/blog/feed.xml public/blog/feed"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.54.0"
